---
title: "Model Metrics - Solutions"
author: "Sarah Romanes"
date: "13 October 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Packages}
library(class)
library(randomForest)
library(ggplot2)
library(caret)
library(rpart)
library(rpart.plot)
```


```{r Setting up the Data}
data <- read.csv("data/diabetes.csv")
data$class <- as.factor(data$class) #remember, classification method require our response variable to be a factor!
```

```{r Explore the data}
head(data)
str(data)


# Seperate Responses (for the case of KNN, and for prediction)
X <- data[,-9] # Everything except last column
y <- data$class
```

# Classifying using rpart

```{r rpart model}
# We can fit the model using the rpart function from library(rpart)

rpart.fit <- rpart(class~., data=data, method="class")
rpart.plot(rpart.fit) # Can also visualise to see the classification rules.
```

```{r Error rate and confusion matrix}

# Resubstitution error rate
fitted.vals <- predict(rpart.fit, X, type="class")
rer.rpart <- mean(fitted.vals!=y)
rer.rpart

# Confusion matrix
confusion.rpart <- confusionMatrix(fitted.vals, y) 
confusion.rpart$table

confusion.rpart$overall["Accuracy"] # Note that Accuracy is just 1-rer.rpart
```

# Classifying using RandomForest

```{r rf model}
# We can fit the model using the rpart function from library(randomForest)

rf.fit <- randomForest(class~., data=data)
```

```{r Error rate and confusion matrix}

# Resubstitution error rate
fitted.vals <- predict(rf.fit, X)
rer.rf <- mean(fitted.vals!=y)
rer.rf

# Confusion matrix
confusion.rf <- confusionMatrix(fitted.vals, y) 
confusion.rf$table

confusion.rf$overall["Accuracy"] # Note that Accuracy is just 1-rer.rf
```

# Classifying using KNN


```{r KNN model/ Error rate and confusion matrix}

# Recall that KNN fits and predicts at the same time. You can pick whatever K value you like, I am going to pick 9 for this example.

fitted.vals <- as.factor(knn(X, X, y, k=9))

# Resubstitution error rate
rer.knn <- mean(fitted.vals!=y)
rer.knn

# Confusion matrix
confusion.knn <- confusionMatrix(fitted.vals, y) 
confusion.knn$table

confusion.knn$overall["Accuracy"] # Note that Accuracy is just 1-rer.knn
```

# Classifying using GLM

```{r glm model}
# We can fit the model using the rpart function from library(randomForest)

glm.fit <- glm(class~., 
               data=data,
               family=binomial(link="logit"))
```

```{r Error rate and confusion matrix}

# Resubstitution error rate
fitted.vals <- as.factor(round(predict(glm.fit, X, type="response")))
rer.glm <- mean(fitted.vals!=y)
rer.glm

# Confusion matrix
confusion.glm <- confusionMatrix(fitted.vals, y) 
confusion.glm$table

confusion.glm$overall["Accuracy"] # Note that Accuracy is just 1-rer.glm
```


